apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golang-k8s-api
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  source:
    path: src/apps/golang-k8s-api/prod
    repoURL: git@github.com:mohamadalsalty/apps-k8s-gitops.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
