app:
  replicas: 2
  containerPort: 8080
  namespace: dev
  replicasMax: 200
  hostname: example.localhost.com
  image:
    repository: "mohamadalsalty/k8s-dash"
    tag: "d02535d1ef533cc02f064c448387d68b87673221"
