apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Release.Name }}
  namespace: {{ .Values.app.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.app.hostname }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.app.containerPort }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: golang-k8s-frontend-dev
            port:
              number: 80
