apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.app.namespace }}-allow-only-namespace-{{ .Release.Name }}
  namespace: {{ .Values.app.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.app.namespace }}
  egress:
  - {}