apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-{{ .Release.Name }}
  namespace: {{ .Values.app.namespace }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       "Deployment"
    name:       "{{ .Release.Name }}"
  updatePolicy:
    updateMode: "Off"