app:
  replicas: 2
  containerPort: 8080
  namespace: prod
  replicasMax: 300
  hostname: example-prod.localhost.com
  image:
    repository: "mohamadalsalty/k8s-dash"
    tag: "1106c6a579aaf488718c7461172e91aa1a1b3e21"
