apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-file
  namespace: dev
data:
  locustfile.py: |
    from locust import HttpUser, TaskSet, task, between

    class UserBehavior(TaskSet):
        @task(1)
        def index(self):
            self.client.get("/clusterinfo")

    class WebsiteUser(HttpUser):
        tasks = [UserBehavior]
        wait_time = between(1, 5)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: locust
      role: master
  template:
    metadata:
      labels:
        app: locust
        role: master
    spec:
      containers:
      - name: locust
        image: locustio/locust
        args: ["-f", "/mnt/locust/locustfile.py", "--master"]
        volumeMounts:
        - name: locust-file
          mountPath: /mnt/locust
        ports:
        - containerPort: 8089
        - containerPort: 5557
      volumes:
      - name: locust-file
        configMap:
          name: locust-file

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: locust
      role: worker
  template:
    metadata:
      labels:
        app: locust
        role: worker
    spec:
      containers:
      - name: locust
        image: locustio/locust
        args: ["-f", "/mnt/locust/locustfile.py", "--worker", "--master-host", "locust-master.dev"]
        volumeMounts:
        - name: locust-file
          mountPath: /mnt/locust
        ports:
        - containerPort: 5557
      volumes:
      - name: locust-file
        configMap:
          name: locust-file

---
apiVersion: v1
kind: Service
metadata:
  name: locust-master
  namespace: dev
spec:
  selector:
    app: locust
    role: master
  ports:
  - name: web
    protocol: TCP
    port: 8089
    targetPort: 8089
  - name: master
    protocol: TCP
    port: 5557
    targetPort: 5557
