# helm upgrade -install external-secrets external-secrets/external-secrets \
#     --set 'serviceAccount.annotations.iam\.gke\.io\/gcp-service-account'="k8s-secret-manager-sa@formidable-bank-427016-h1.iam.gserviceaccount.com" \
#     --namespace ext-secrets \
#     --create-namespace \
#     --debug \
#     --wait

# # kubectl create secret generic gcp-secret-manager-credentials --from-file=key.json=/tmp/sa.acc.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
  namespace: ext-secrets
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-secret-manager-credentials
            key: key.json    
            namespace: default
      projectID: formidable-bank-427016-h1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dotenv-golang-k8s-api
  namespace: dev
spec:
  refreshInterval: 10s            # rate SecretManager pulls GCPSM, Low refereshInternval for demo purpose,Set this value based based on apps
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store               # name of the ClusterSecretStore or you can also reference SecretStore
  target:
    name: golang-k8s-api                # name of the k8s Secret to be created
  data:
  - secretKey: dotenv-golang-k8s-api            # name of secretkey it can be any name            
    remoteRef:
      key: k8s_secret_sa            # name of the GCPSM secret key

