apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
        volumeMounts:
        - name: dotenv-secret
          mountPath: /home/node/app/.env
          subPath: dotenv-golang-k8s-api-dev
        ports:
        - containerPort: {{ .Values.app.containerPort }}
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"      
      volumes:
      - name: dotenv-secret
        secret:
          secretName: golang-k8s-api-dev
status: {}
